# Generated by Django 3.2.8 on 2021-12-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapists',
            options={'verbose_name': 'Therapist', 'verbose_name_plural': 'Therapists'},
        ),
    ]
