# Generated by Django 3.2.8 on 2021-12-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists_list', '0002_alter_therapists_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='photo',
            field=models.ImageField(upload_to='therapists_photo/', verbose_name='photo'),
        ),
    ]
