# Generated by Django 3.2.8 on 2021-12-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('anons', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='article_images/')),
                ('full_text', models.TextField()),
            ],
        ),
    ]
